# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 500

# Don't break prompt in two lines
[line_break]
disabled = true

[username]
show_always = true

[hostname]
ssh_only = false

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""

[python]
disabled = true

[git_status]
stashed = "" # hide stashed

[rust]
disabled = true

[c]
disabled = true

[package]
disabled = true

