# Don't print a new line at the start of the prompt
add_newline = false

# Don't break prompt in two lines
[line_break]
disabled = true

[character]
symbol = ">"

[username]
show_always = true

[hostname]
ssh_only = false

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""

[git_status]
modified_count.enabled = true
untracked_count.enabled = true
show_sync_count = true
stashed = "" # hide stashed

[rust]
disabled = true

[python]
disabled = true

[package]
disabled = true
